lang: fr
title: Samantha Kaufmann-Deblock
description: Template pour la cr√©ation d'un repo type CV
theme: bulma-clean-theme

url: https://github.com/gorinje/craft-the-cv2

force_theme: light
permalink: pretty
lang: fr
theme_color: '#FFB5C0'
fixed_navbar: top
show_logo: true

collections:
  products: 
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false

plugins:
  - jekyll-remote-include

